services:
    db:
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 3s
            retries: 5
    redis:
        image: redis:7.0.15-alpine
        ports:
            - '6380:6379'
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 5
    web:
        build: .
        command: bash -c "bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0"
        volumes:
            - .:/rails
        ports:
            - '3000:3000'
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
        environment:
            DATABASE_URL: postgresql://postgres:password@db:5432/store_development
            REDIS_URL: redis://redis:6379/0
    sidekiq:
        build: .
        command: bundle exec sidekiq -C config/sidekiq.yml
        volumes:
            - .:/rails
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
        environment:
            DATABASE_URL: postgresql://postgres:password@db:5432/store_development
            REDIS_URL: redis://redis:6379/0
    test:
        build: .
        command: bash -c "bundle exec rails db:prepare && bundle exec rspec"
        volumes:
            - .:/rails
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
        environment:
            RAILS_ENV: test
            DATABASE_URL: postgresql://postgres:password@db:5432/store_test
            REDIS_URL: redis://redis:6379/0

volumes:
    postgres_data:
    redis_data:
